UPDATE Country SET italian_name="Afghanistan" WHERE country_id=1;
UPDATE Country SET italian_name="Isole Aland" WHERE country_id=2;
UPDATE Country SET italian_name="Albania" WHERE country_id=3;
UPDATE Country SET italian_name="Algeria" WHERE country_id=4;
UPDATE Country SET italian_name="Samoa Americane" WHERE country_id=5;
UPDATE Country SET italian_name="Andorra" WHERE country_id=6;
UPDATE Country SET italian_name="Angola" WHERE country_id=7;
UPDATE Country SET italian_name="Anguilla" WHERE country_id=8;
UPDATE Country SET italian_name="Antartide" WHERE country_id=9;
UPDATE Country SET italian_name="Antigua e Barbuda" WHERE country_id=10;
UPDATE Country SET italian_name="Argentina" WHERE country_id=11;
UPDATE Country SET italian_name="Armenia" WHERE country_id=12;
UPDATE Country SET italian_name="Aruba" WHERE country_id=13;
UPDATE Country SET italian_name="L'Australia" WHERE country_id=14;
UPDATE Country SET italian_name="Austria" WHERE country_id=15;
UPDATE Country SET italian_name="Azerbaijan" WHERE country_id=16;
UPDATE Country SET italian_name="Bahamas" WHERE country_id=17;
UPDATE Country SET italian_name="Bahrain" WHERE country_id=18;
UPDATE Country SET italian_name="Bangladesh" WHERE country_id=19;
UPDATE Country SET italian_name="Barbados" WHERE country_id=20;
UPDATE Country SET italian_name="Bielorussia" WHERE country_id=21;
UPDATE Country SET italian_name="Belgio" WHERE country_id=22;
UPDATE Country SET italian_name="Belize" WHERE country_id=23;
UPDATE Country SET italian_name="Benin" WHERE country_id=24;
UPDATE Country SET italian_name="Bermuda" WHERE country_id=25;
UPDATE Country SET italian_name="Bhutan" WHERE country_id=26;
UPDATE Country SET italian_name="Bolivia" WHERE country_id=27;
UPDATE Country SET italian_name="Dutch Caribbean" WHERE country_id=28;
UPDATE Country SET italian_name="Bosnia-Erzegovina" WHERE country_id=29;
UPDATE Country SET italian_name="Botswana" WHERE country_id=30;
UPDATE Country SET italian_name="Isola Bouvet" WHERE country_id=31;
UPDATE Country SET italian_name="Brasile" WHERE country_id=32;
UPDATE Country SET italian_name="Territorio britannico dell'Oceano Indiano" WHERE country_id=33;
UPDATE Country SET italian_name="Brunei Darussalam" WHERE country_id=34;
UPDATE Country SET italian_name="Bulgaria" WHERE country_id=35;
UPDATE Country SET italian_name="Burkina Faso" WHERE country_id=36;
UPDATE Country SET italian_name="Burundi" WHERE country_id=37;
UPDATE Country SET italian_name="Cambogia" WHERE country_id=38;
UPDATE Country SET italian_name="Camerun" WHERE country_id=39;
UPDATE Country SET italian_name="Canada" WHERE country_id=40;
UPDATE Country SET italian_name="Capo Verde" WHERE country_id=41;
UPDATE Country SET italian_name="Isole Cayman" WHERE country_id=42;
UPDATE Country SET italian_name="Repubblica Centrafricana" WHERE country_id=43;
UPDATE Country SET italian_name="Ciad" WHERE country_id=44;
UPDATE Country SET italian_name="Cile" WHERE country_id=45;
UPDATE Country SET italian_name="Cina" WHERE country_id=46;
UPDATE Country SET italian_name="Christmas Island, Isola di Natale" WHERE country_id=47;
UPDATE Country SET italian_name="Isole Cocos" WHERE country_id=48;
UPDATE Country SET italian_name="Colombia" WHERE country_id=49;
UPDATE Country SET italian_name="Comores" WHERE country_id=50;
UPDATE Country SET italian_name="Repubblica del Congo" WHERE country_id=51;
UPDATE Country SET italian_name="Isole Cook" WHERE country_id=52;
UPDATE Country SET italian_name="Costa Rica" WHERE country_id=53;
UPDATE Country SET italian_name="Costa d'Avorio" WHERE country_id=54;
UPDATE Country SET italian_name="Croazia" WHERE country_id=55;
UPDATE Country SET italian_name="Cuba" WHERE country_id=56;
UPDATE Country SET italian_name="Curacao" WHERE country_id=57;
UPDATE Country SET italian_name="Cipro" WHERE country_id=58;
UPDATE Country SET italian_name="Repubblica Ceca" WHERE country_id=59;
UPDATE Country SET italian_name="RDC" WHERE country_id=60;
UPDATE Country SET italian_name="Danimarca" WHERE country_id=61;
UPDATE Country SET italian_name="Gibuti" WHERE country_id=62;
UPDATE Country SET italian_name="Dominica" WHERE country_id=63;
UPDATE Country SET italian_name="Repubblica Dominicana" WHERE country_id=64;
UPDATE Country SET italian_name="Ecuador" WHERE country_id=65;
UPDATE Country SET italian_name="Egiipto" WHERE country_id=66;
UPDATE Country SET italian_name="El Salvador" WHERE country_id=67;
UPDATE Country SET italian_name="Guinea Equatoriale" WHERE country_id=68;
UPDATE Country SET italian_name="Eritrea" WHERE country_id=69;
UPDATE Country SET italian_name="Estonia" WHERE country_id=70;
UPDATE Country SET italian_name="Etiopia" WHERE country_id=71;
UPDATE Country SET italian_name="Isole Falkland" WHERE country_id=72;
UPDATE Country SET italian_name="Isole Faroe" WHERE country_id=73;
UPDATE Country SET italian_name="Fiji" WHERE country_id=74;
UPDATE Country SET italian_name="Finlandia" WHERE country_id=75;
UPDATE Country SET italian_name="Francia" WHERE country_id=76;
UPDATE Country SET italian_name="Guiana francese" WHERE country_id=77;
UPDATE Country SET italian_name="Polinesia Francese" WHERE country_id=78;
UPDATE Country SET italian_name="Frencesas Territori del Sud" WHERE country_id=79;
UPDATE Country SET italian_name="Gabon" WHERE country_id=80;
UPDATE Country SET italian_name="Gambia" WHERE country_id=81;
UPDATE Country SET italian_name="Georgia" WHERE country_id=82;
UPDATE Country SET italian_name="Germania" WHERE country_id=83;
UPDATE Country SET italian_name="Ghana" WHERE country_id=84;
UPDATE Country SET italian_name="Gibilterra" WHERE country_id=85;
UPDATE Country SET italian_name="Grecia" WHERE country_id=86;
UPDATE Country SET italian_name="Groenlandia" WHERE country_id=87;
UPDATE Country SET italian_name="Granada" WHERE country_id=88;
UPDATE Country SET italian_name="Guadalupe" WHERE country_id=89;
UPDATE Country SET italian_name="Guam" WHERE country_id=90;
UPDATE Country SET italian_name="Guatemala" WHERE country_id=91;
UPDATE Country SET italian_name="Guernsey" WHERE country_id=92;
UPDATE Country SET italian_name="Guinea Repubblica" WHERE country_id=93;
UPDATE Country SET italian_name="Guinea Bissau" WHERE country_id=94;
UPDATE Country SET italian_name="Guyana" WHERE country_id=95;
UPDATE Country SET italian_name="Haiti" WHERE country_id=96;
UPDATE Country SET italian_name="Heard e Isole McDonald" WHERE country_id=97;
UPDATE Country SET italian_name="Honduras" WHERE country_id=98;
UPDATE Country SET italian_name="Hong Kong" WHERE country_id=99;
UPDATE Country SET italian_name="Ungheria" WHERE country_id=100;
UPDATE Country SET italian_name="Islanda" WHERE country_id=101;
UPDATE Country SET italian_name="India" WHERE country_id=102;
UPDATE Country SET italian_name="Indonesia" WHERE country_id=103;
UPDATE Country SET italian_name="Iran" WHERE country_id=104;
UPDATE Country SET italian_name="Iraq" WHERE country_id=105;
UPDATE Country SET italian_name="Irlanda" WHERE country_id=106;
UPDATE Country SET italian_name="Isola di Man" WHERE country_id=107;
UPDATE Country SET italian_name="Israele" WHERE country_id=108;
UPDATE Country SET italian_name="Italia" WHERE country_id=109;
UPDATE Country SET italian_name="Giamaica" WHERE country_id=110;
UPDATE Country SET italian_name="Giappone" WHERE country_id=111;
UPDATE Country SET italian_name="Jersey" WHERE country_id=112;
UPDATE Country SET italian_name="Giordania" WHERE country_id=113;
UPDATE Country SET italian_name="Kazakhstan" WHERE country_id=114;
UPDATE Country SET italian_name="Kenya" WHERE country_id=115;
UPDATE Country SET italian_name="Kiribati" WHERE country_id=116;
UPDATE Country SET italian_name="Kosovo" WHERE country_id=117;
UPDATE Country SET italian_name="Kuwait" WHERE country_id=118;
UPDATE Country SET italian_name="Kirghizistan" WHERE country_id=119;
UPDATE Country SET italian_name="Laos" WHERE country_id=120;
UPDATE Country SET italian_name="Lettonia" WHERE country_id=121;
UPDATE Country SET italian_name="Libano" WHERE country_id=122;
UPDATE Country SET italian_name="Lesotho" WHERE country_id=123;
UPDATE Country SET italian_name="Liberia" WHERE country_id=124;
UPDATE Country SET italian_name="Libia" WHERE country_id=125;
UPDATE Country SET italian_name="Liechtenstein" WHERE country_id=126;
UPDATE Country SET italian_name="Lituania" WHERE country_id=127;
UPDATE Country SET italian_name="Lussemburgo" WHERE country_id=128;
UPDATE Country SET italian_name="Macao" WHERE country_id=129;
UPDATE Country SET italian_name="Macedonia" WHERE country_id=130;
UPDATE Country SET italian_name="Madagascar" WHERE country_id=131;
UPDATE Country SET italian_name="Malawi" WHERE country_id=132;
UPDATE Country SET italian_name="Malesia" WHERE country_id=133;
UPDATE Country SET italian_name="Maldive" WHERE country_id=134;
UPDATE Country SET italian_name="Mali" WHERE country_id=135;
UPDATE Country SET italian_name="Malta" WHERE country_id=136;
UPDATE Country SET italian_name="Isole Marshall" WHERE country_id=137;
UPDATE Country SET italian_name="Martinica" WHERE country_id=138;
UPDATE Country SET italian_name="Mauritania" WHERE country_id=139;
UPDATE Country SET italian_name="Mauricio" WHERE country_id=140;
UPDATE Country SET italian_name="Mayotte" WHERE country_id=141;
UPDATE Country SET italian_name="Messico" WHERE country_id=142;
UPDATE Country SET italian_name="Micronesia" WHERE country_id=143;
UPDATE Country SET italian_name="Modavia" WHERE country_id=144;
UPDATE Country SET italian_name="Monaco" WHERE country_id=145;
UPDATE Country SET italian_name="Mongolia" WHERE country_id=146;
UPDATE Country SET italian_name="Montenegro" WHERE country_id=147;
UPDATE Country SET italian_name="Montserrat" WHERE country_id=148;
UPDATE Country SET italian_name="Marocco" WHERE country_id=149;
UPDATE Country SET italian_name="Mozambico" WHERE country_id=150;
UPDATE Country SET italian_name="Myanmar (Birmania)" WHERE country_id=151;
UPDATE Country SET italian_name="Namibia" WHERE country_id=152;
UPDATE Country SET italian_name="Nauru" WHERE country_id=153;
UPDATE Country SET italian_name="Nepal" WHERE country_id=154;
UPDATE Country SET italian_name="Paesi Bassi, Paesi Bassi" WHERE country_id=155;
UPDATE Country SET italian_name="Nuova Caledonia" WHERE country_id=156;
UPDATE Country SET italian_name="NZ" WHERE country_id=157;
UPDATE Country SET italian_name="Nicaragua" WHERE country_id=158;
UPDATE Country SET italian_name="Niger" WHERE country_id=159;
UPDATE Country SET italian_name="Nigeria" WHERE country_id=160;
UPDATE Country SET italian_name="Niue" WHERE country_id=161;
UPDATE Country SET italian_name="Norfolk Island" WHERE country_id=162;
UPDATE Country SET italian_name="Corea del Nord" WHERE country_id=163;
UPDATE Country SET italian_name="Isole Marianne Settentrionali" WHERE country_id=164;
UPDATE Country SET italian_name="Norvegia" WHERE country_id=165;
UPDATE Country SET italian_name="Oman" WHERE country_id=166;
UPDATE Country SET italian_name="Pakistan" WHERE country_id=167;
UPDATE Country SET italian_name="Palau" WHERE country_id=168;
UPDATE Country SET italian_name="Palestina" WHERE country_id=169;
UPDATE Country SET italian_name="Panama" WHERE country_id=170;
UPDATE Country SET italian_name="Papua Nuova Guinea" WHERE country_id=171;
UPDATE Country SET italian_name="Paraguay" WHERE country_id=172;
UPDATE Country SET italian_name="Peru" WHERE country_id=173;
UPDATE Country SET italian_name="Filippine" WHERE country_id=174;
UPDATE Country SET italian_name="Pitcairn" WHERE country_id=175;
UPDATE Country SET italian_name="Polonia" WHERE country_id=176;
UPDATE Country SET italian_name="Portogallo" WHERE country_id=177;
UPDATE Country SET italian_name="Puerto Rico" WHERE country_id=178;
UPDATE Country SET italian_name="Qatar" WHERE country_id=179;
UPDATE Country SET italian_name="Riunione" WHERE country_id=180;
UPDATE Country SET italian_name="Romania" WHERE country_id=181;
UPDATE Country SET italian_name="Federazione Russa" WHERE country_id=182;
UPDATE Country SET italian_name="Ruanda" WHERE country_id=183;
UPDATE Country SET italian_name="San Barolome" WHERE country_id=184;
UPDATE Country SET italian_name="Santa Elena" WHERE country_id=185;
UPDATE Country SET italian_name="St. Kitts e Nevis" WHERE country_id=186;
UPDATE Country SET italian_name="St. Lucia" WHERE country_id=187;
UPDATE Country SET italian_name="San Martin" WHERE country_id=188;
UPDATE Country SET italian_name="Saint Pierre e Miquelon" WHERE country_id=189;
UPDATE Country SET italian_name="Saint Vincent e Grenadine" WHERE country_id=190;
UPDATE Country SET italian_name="Samoa" WHERE country_id=191;
UPDATE Country SET italian_name="San Marino" WHERE country_id=192;
UPDATE Country SET italian_name="Sao Tome e Principe" WHERE country_id=193;
UPDATE Country SET italian_name="Arabia Saudita" WHERE country_id=194;
UPDATE Country SET italian_name="Senegal" WHERE country_id=195;
UPDATE Country SET italian_name="Serbia" WHERE country_id=196;
UPDATE Country SET italian_name="Seychelles" WHERE country_id=197;
UPDATE Country SET italian_name="Sierra Leone" WHERE country_id=198;
UPDATE Country SET italian_name="Singapore" WHERE country_id=199;
UPDATE Country SET italian_name="Sint Maarten" WHERE country_id=200;
UPDATE Country SET italian_name="Slovacchia" WHERE country_id=201;
UPDATE Country SET italian_name="Slovenia" WHERE country_id=202;
UPDATE Country SET italian_name="Isole Salomone" WHERE country_id=203;
UPDATE Country SET italian_name="Somalia" WHERE country_id=204;
UPDATE Country SET italian_name="Sud Africa" WHERE country_id=205;
UPDATE Country SET italian_name="Sudo Georgia e Isole Sandwich del Sud" WHERE country_id=206;
UPDATE Country SET italian_name="Corea del Sud" WHERE country_id=207;
UPDATE Country SET italian_name="Sud Sudan" WHERE country_id=208;
UPDATE Country SET italian_name="Spagna" WHERE country_id=209;
UPDATE Country SET italian_name="Sri Lanka" WHERE country_id=210;
UPDATE Country SET italian_name="Sudan" WHERE country_id=211;
UPDATE Country SET italian_name="Suriname" WHERE country_id=212;
UPDATE Country SET italian_name="Jan Mayen Island e Arcipelago Svalb" WHERE country_id=213;
UPDATE Country SET italian_name="Swaziland" WHERE country_id=214;
UPDATE Country SET italian_name="Svezia" WHERE country_id=215;
UPDATE Country SET italian_name="Svizzera" WHERE country_id=216;
UPDATE Country SET italian_name="Siria" WHERE country_id=217;
UPDATE Country SET italian_name="Taiwan" WHERE country_id=218;
UPDATE Country SET italian_name="Tadjikistan" WHERE country_id=219;
UPDATE Country SET italian_name="Tanzania" WHERE country_id=220;
UPDATE Country SET italian_name="Thailandia" WHERE country_id=221;
UPDATE Country SET italian_name="Timor Est" WHERE country_id=222;
UPDATE Country SET italian_name="Togo" WHERE country_id=223;
UPDATE Country SET italian_name="Tokelau" WHERE country_id=224;
UPDATE Country SET italian_name="Tonga" WHERE country_id=225;
UPDATE Country SET italian_name="Trinidad e Tobago" WHERE country_id=226;
UPDATE Country SET italian_name="Tuez" WHERE country_id=227;
UPDATE Country SET italian_name="Turchia" WHERE country_id=228;
UPDATE Country SET italian_name="Turkmenistan" WHERE country_id=229;
UPDATE Country SET italian_name="Turks e Caicos" WHERE country_id=230;
UPDATE Country SET italian_name="Tuvalu" WHERE country_id=231;
UPDATE Country SET italian_name="Uganda" WHERE country_id=232;
UPDATE Country SET italian_name="Ucraina" WHERE country_id=233;
UPDATE Country SET italian_name="Emirati Arabi Uniti" WHERE country_id=234;
UPDATE Country SET italian_name="UK" WHERE country_id=235;
UPDATE Country SET italian_name="US" WHERE country_id=236;
UPDATE Country SET italian_name="Isole Minori degli Stati Uniti" WHERE country_id=237;
UPDATE Country SET italian_name="Uruguay" WHERE country_id=238;
UPDATE Country SET italian_name="Uzbekistan" WHERE country_id=239;
UPDATE Country SET italian_name="Vanuatu" WHERE country_id=240;
UPDATE Country SET italian_name="Città del Vaticano" WHERE country_id=241;
UPDATE Country SET italian_name="Venezuela" WHERE country_id=242;
UPDATE Country SET italian_name="Vietnam" WHERE country_id=243;
UPDATE Country SET italian_name="Isole Vergini Britanniche" WHERE country_id=244;
UPDATE Country SET italian_name="Isole Vergini Americane" WHERE country_id=245;
UPDATE Country SET italian_name="Wallis e Futuna" WHERE country_id=246;
UPDATE Country SET italian_name="Sahara occidentale" WHERE country_id=247;
UPDATE Country SET italian_name="Yemen" WHERE country_id=248;
UPDATE Country SET italian_name="Zambia" WHERE country_id=249;
UPDATE Country SET italian_name="Zimbabwe" WHERE country_id=250;