ALTER TABLE `country_t` ADD `spanish_name` VARCHAR( 150 ) NULL;
Update `country_t` SET spanish_name = "Afganist&aacute;n" WHERE iso2 = "AF";
Update `country_t` SET spanish_name = "Islas &Acirc;land" WHERE iso2 = "AX";
Update `country_t` SET spanish_name = "Albania" WHERE iso2 = "AL";
Update `country_t` SET spanish_name = "Argelia" WHERE iso2 = "DZ";
Update `country_t` SET spanish_name = "Samoa Americana" WHERE iso2 = "AS";
Update `country_t` SET spanish_name = "Andorra" WHERE iso2 = "AD";
Update `country_t` SET spanish_name = "Angola" WHERE iso2 = "AO";
Update `country_t` SET spanish_name = "Anguilla" WHERE iso2 = "AI";
Update `country_t` SET spanish_name = "Ant&aacute;rtida" WHERE iso2 = "AQ";
Update `country_t` SET spanish_name = "Antigua y Barbuda" WHERE iso2 = "AG";
Update `country_t` SET spanish_name = "Argentina" WHERE iso2 = "AR";
Update `country_t` SET spanish_name = "Armenia" WHERE iso2 = "AM";
Update `country_t` SET spanish_name = "Aruba" WHERE iso2 = "AW";
Update `country_t` SET spanish_name = "Australia" WHERE iso2 = "AU";
Update `country_t` SET spanish_name = "Austria" WHERE iso2 = "AT";
Update `country_t` SET spanish_name = "Azerbaiy&aacute;n" WHERE iso2 = "AZ";
Update `country_t` SET spanish_name = "Bahamas" WHERE iso2 = "BS";
Update `country_t` SET spanish_name = "Bahrein" WHERE iso2 = "BH";
Update `country_t` SET spanish_name = "Bangladesh" WHERE iso2 = "BD";
Update `country_t` SET spanish_name = "Barbados" WHERE iso2 = "BB";
Update `country_t` SET spanish_name = "Bielorrusia" WHERE iso2 = "BY";
Update `country_t` SET spanish_name = "B&eacute;lgica" WHERE iso2 = "BE";
Update `country_t` SET spanish_name = "Belice" WHERE iso2 = "BZ";
Update `country_t` SET spanish_name = "Ben&iacute;n" WHERE iso2 = "BJ";
Update `country_t` SET spanish_name = "Bermudas" WHERE iso2 = "BM";
Update `country_t` SET spanish_name = "But&aacute;n" WHERE iso2 = "BT";
Update `country_t` SET spanish_name = "Bolivia" WHERE iso2 = "BO";
Update `country_t` SET spanish_name = "Caribe Neerland&eacute;s" WHERE iso2 = "BQ";
Update `country_t` SET spanish_name = "Bosnia-Herzegovina" WHERE iso2 = "BA";
Update `country_t` SET spanish_name = "Botswana" WHERE iso2 = "BW";
Update `country_t` SET spanish_name = "Isla Bouvet" WHERE iso2 = "BV";
Update `country_t` SET spanish_name = "Brasil" WHERE iso2 = "BR";
Update `country_t` SET spanish_name = "Territorio Brit&aacute;nico del Oc&eacute;ano Indico" WHERE iso2 = "IO";
Update `country_t` SET spanish_name = "Brunei Darussalam" WHERE iso2 = "BN";
Update `country_t` SET spanish_name = "Bulgaria" WHERE iso2 = "BG";
Update `country_t` SET spanish_name = "Burkina Faso" WHERE iso2 = "BF";
Update `country_t` SET spanish_name = "Burundi" WHERE iso2 = "BI";
Update `country_t` SET spanish_name = "Camboya" WHERE iso2 = "KH";
Update `country_t` SET spanish_name = "Camer&uacute;n" WHERE iso2 = "CM";
Update `country_t` SET spanish_name = "Canad&aacute;" WHERE iso2 = "CA";
Update `country_t` SET spanish_name = "Cabo Verde" WHERE iso2 = "CV";
Update `country_t` SET spanish_name = "Islas Caim&aacute;n" WHERE iso2 = "KY";
Update `country_t` SET spanish_name = "Rep&uacute;blica Centroafricana" WHERE iso2 = "CF";
Update `country_t` SET spanish_name = "Chad" WHERE iso2 = "TD";
Update `country_t` SET spanish_name = "Chile" WHERE iso2 = "CL";
Update `country_t` SET spanish_name = "China" WHERE iso2 = "CN";
Update `country_t` SET spanish_name = "Isla de Navidad, Isla Christmas" WHERE iso2 = "CX";
Update `country_t` SET spanish_name = "Islas Cocos" WHERE iso2 = "CC";
Update `country_t` SET spanish_name = "Colombia" WHERE iso2 = "CO";
Update `country_t` SET spanish_name = "Comores" WHERE iso2 = "KM";
Update `country_t` SET spanish_name = "Rep&uacute;blica del Congo" WHERE iso2 = "CG";
Update `country_t` SET spanish_name = "Islas Cook" WHERE iso2 = "CK";
Update `country_t` SET spanish_name = "Costa Rica" WHERE iso2 = "CR";
Update `country_t` SET spanish_name = "Costa de Marfil" WHERE iso2 = "CI";
Update `country_t` SET spanish_name = "Croacia" WHERE iso2 = "HR";
Update `country_t` SET spanish_name = "Cuba" WHERE iso2 = "CU";
Update `country_t` SET spanish_name = "Curazao" WHERE iso2 = "CW";
Update `country_t` SET spanish_name = "Chipre" WHERE iso2 = "CY";
Update `country_t` SET spanish_name = "Rep&uacute;blica Checa" WHERE iso2 = "CZ";
Update `country_t` SET spanish_name = "Rep&uacute;blica Democr&aacute;tica del Congo" WHERE iso2 = "CD";
Update `country_t` SET spanish_name = "Dinamarca" WHERE iso2 = "DK";
Update `country_t` SET spanish_name = "Djibouti" WHERE iso2 = "DJ";
Update `country_t` SET spanish_name = "Dominica" WHERE iso2 = "DM";
Update `country_t` SET spanish_name = "Rep&uacute;blica Dominicana" WHERE iso2 = "DO";
Update `country_t` SET spanish_name = "Ecuador" WHERE iso2 = "EC";
Update `country_t` SET spanish_name = "Egiipto" WHERE iso2 = "EG";
Update `country_t` SET spanish_name = "El Salvador" WHERE iso2 = "SV";
Update `country_t` SET spanish_name = "Guinea Ecuatorial" WHERE iso2 = "GQ";
Update `country_t` SET spanish_name = "Eritrea" WHERE iso2 = "ER";
Update `country_t` SET spanish_name = "Estonia" WHERE iso2 = "EE";
Update `country_t` SET spanish_name = "Etiop&iacute;a" WHERE iso2 = "ET";
Update `country_t` SET spanish_name = "Islas Malvinas" WHERE iso2 = "FK";
Update `country_t` SET spanish_name = "Islas Feroe" WHERE iso2 = "FO";
Update `country_t` SET spanish_name = "Fiyi" WHERE iso2 = "FJ";
Update `country_t` SET spanish_name = "Finlandia" WHERE iso2 = "FI";
Update `country_t` SET spanish_name = "Francia" WHERE iso2 = "FR";
Update `country_t` SET spanish_name = "Guayana Francesa" WHERE iso2 = "GF";
Update `country_t` SET spanish_name = "Polinesia Francesa" WHERE iso2 = "PF";
Update `country_t` SET spanish_name = "Tierras Australes Frencesas" WHERE iso2 = "TF";
Update `country_t` SET spanish_name = "Gab&oacute;n" WHERE iso2 = "GA";
Update `country_t` SET spanish_name = "Gambia" WHERE iso2 = "GM";
Update `country_t` SET spanish_name = "Georgia" WHERE iso2 = "GE";
Update `country_t` SET spanish_name = "Alemania" WHERE iso2 = "DE";
Update `country_t` SET spanish_name = "Ghana" WHERE iso2 = "GH";
Update `country_t` SET spanish_name = "Gibraltar" WHERE iso2 = "GI";
Update `country_t` SET spanish_name = "Grecia" WHERE iso2 = "GR";
Update `country_t` SET spanish_name = "Groenlandia" WHERE iso2 = "GL";
Update `country_t` SET spanish_name = "Granada" WHERE iso2 = "GD";
Update `country_t` SET spanish_name = "Guadalupe" WHERE iso2 = "GP";
Update `country_t` SET spanish_name = "Guam" WHERE iso2 = "GU";
Update `country_t` SET spanish_name = "Guatemala" WHERE iso2 = "GT";
Update `country_t` SET spanish_name = "Guernsey" WHERE iso2 = "GG";
Update `country_t` SET spanish_name = "Rep&uacute;blica Guinea" WHERE iso2 = "GN";
Update `country_t` SET spanish_name = "Guinea Bissau" WHERE iso2 = "GW";
Update `country_t` SET spanish_name = "Guyana" WHERE iso2 = "GY";
Update `country_t` SET spanish_name = "Haiti" WHERE iso2 = "HT";
Update `country_t` SET spanish_name = "Islas de Heard y McDonald" WHERE iso2 = "HM";
Update `country_t` SET spanish_name = "Honduras" WHERE iso2 = "HN";
Update `country_t` SET spanish_name = "Hong Kong" WHERE iso2 = "HK";
Update `country_t` SET spanish_name = "Hungr&iacute;a" WHERE iso2 = "HU";
Update `country_t` SET spanish_name = "Islandia" WHERE iso2 = "IS";
Update `country_t` SET spanish_name = "India" WHERE iso2 = "IN";
Update `country_t` SET spanish_name = "Indonesia" WHERE iso2 = "ID";
Update `country_t` SET spanish_name = "Ir&aacute;n" WHERE iso2 = "IR";
Update `country_t` SET spanish_name = "Iraq" WHERE iso2 = "IQ";
Update `country_t` SET spanish_name = "Irlanda" WHERE iso2 = "IE";
Update `country_t` SET spanish_name = "Isla Man" WHERE iso2 = "IM";
Update `country_t` SET spanish_name = "Israel" WHERE iso2 = "IL";
Update `country_t` SET spanish_name = "Italia" WHERE iso2 = "IT";
Update `country_t` SET spanish_name = "Jamaica" WHERE iso2 = "JM";
Update `country_t` SET spanish_name = "Jap&oacute;n" WHERE iso2 = "JP";
Update `country_t` SET spanish_name = "Jersey" WHERE iso2 = "JE";
Update `country_t` SET spanish_name = "Jordania" WHERE iso2 = "JO";
Update `country_t` SET spanish_name = "Kazajst&aacute;n" WHERE iso2 = "KZ";
Update `country_t` SET spanish_name = "Kenia" WHERE iso2 = "KE";
Update `country_t` SET spanish_name = "Kiribati" WHERE iso2 = "KI";
Update `country_t` SET spanish_name = "Kosovo" WHERE iso2 = "XK";
Update `country_t` SET spanish_name = "Kuwait" WHERE iso2 = "KW";
Update `country_t` SET spanish_name = "Kirguist&aacute;n" WHERE iso2 = "KG";
Update `country_t` SET spanish_name = "Laos" WHERE iso2 = "LA";
Update `country_t` SET spanish_name = "Letonia" WHERE iso2 = "LV";
Update `country_t` SET spanish_name = "L&iacute;bano" WHERE iso2 = "LB";
Update `country_t` SET spanish_name = "Lesotho" WHERE iso2 = "LS";
Update `country_t` SET spanish_name = "Liberia" WHERE iso2 = "LR";
Update `country_t` SET spanish_name = "Libia" WHERE iso2 = "LY";
Update `country_t` SET spanish_name = "Liechtenstein" WHERE iso2 = "LI";
Update `country_t` SET spanish_name = "Lituania" WHERE iso2 = "LT";
Update `country_t` SET spanish_name = "Luxemburgo" WHERE iso2 = "LU";
Update `country_t` SET spanish_name = "Macao" WHERE iso2 = "MO";
Update `country_t` SET spanish_name = "Macedonia" WHERE iso2 = "MK";
Update `country_t` SET spanish_name = "Madagascar" WHERE iso2 = "MG";
Update `country_t` SET spanish_name = "Malawi" WHERE iso2 = "MW";
Update `country_t` SET spanish_name = "Malasia" WHERE iso2 = "MY";
Update `country_t` SET spanish_name = "Maldivas" WHERE iso2 = "MV";
Update `country_t` SET spanish_name = "Mal&iacute;" WHERE iso2 = "ML";
Update `country_t` SET spanish_name = "Malta" WHERE iso2 = "MT";
Update `country_t` SET spanish_name = "Islas Marshall" WHERE iso2 = "MH";
Update `country_t` SET spanish_name = "Martinica" WHERE iso2 = "MQ";
Update `country_t` SET spanish_name = "Mauritania" WHERE iso2 = "MR";
Update `country_t` SET spanish_name = "Mauricio" WHERE iso2 = "MU";
Update `country_t` SET spanish_name = "Mayotte" WHERE iso2 = "YT";
Update `country_t` SET spanish_name = "M&eacute;xico" WHERE iso2 = "MX";
Update `country_t` SET spanish_name = "Micronesia" WHERE iso2 = "FM";
Update `country_t` SET spanish_name = "Modavia" WHERE iso2 = "MD";
Update `country_t` SET spanish_name = "M&oacute;naco" WHERE iso2 = "MC";
Update `country_t` SET spanish_name = "Mongolia" WHERE iso2 = "MN";
Update `country_t` SET spanish_name = "Montenegro" WHERE iso2 = "ME";
Update `country_t` SET spanish_name = "Montserrat" WHERE iso2 = "MS";
Update `country_t` SET spanish_name = "Marruecos" WHERE iso2 = "MA";
Update `country_t` SET spanish_name = "Mozambique" WHERE iso2 = "MZ";
Update `country_t` SET spanish_name = "Myanmar (Birmania)" WHERE iso2 = "MM";
Update `country_t` SET spanish_name = "Namibia" WHERE iso2 = "NA";
Update `country_t` SET spanish_name = "Nauru" WHERE iso2 = "NR";
Update `country_t` SET spanish_name = "Nepal" WHERE iso2 = "NP";
Update `country_t` SET spanish_name = "Pa&iacute;ses Bajos, Holanda" WHERE iso2 = "NL";
Update `country_t` SET spanish_name = "Nueva Caledonia" WHERE iso2 = "NC";
Update `country_t` SET spanish_name = "Nueva Zelanda" WHERE iso2 = "NZ";
Update `country_t` SET spanish_name = "Nicaragua" WHERE iso2 = "NI";
Update `country_t` SET spanish_name = "Niger" WHERE iso2 = "NE";
Update `country_t` SET spanish_name = "Nigeria" WHERE iso2 = "NG";
Update `country_t` SET spanish_name = "Niue" WHERE iso2 = "NU";
Update `country_t` SET spanish_name = "Norfolk Island" WHERE iso2 = "NF";
Update `country_t` SET spanish_name = "Corea del Norte" WHERE iso2 = "KP";
Update `country_t` SET spanish_name = "Marianas del Norte" WHERE iso2 = "MP";
Update `country_t` SET spanish_name = "Noruega" WHERE iso2 = "NO";
Update `country_t` SET spanish_name = "Om&aacute;man" WHERE iso2 = "OM";
Update `country_t` SET spanish_name = "Pakist&aacute;n" WHERE iso2 = "PK";
Update `country_t` SET spanish_name = "Palau" WHERE iso2 = "PW";
Update `country_t` SET spanish_name = "Palestina" WHERE iso2 = "PS";
Update `country_t` SET spanish_name = "Panam&aacute;" WHERE iso2 = "PA";
Update `country_t` SET spanish_name = "Pap&uacute;a-Nueva Guinea" WHERE iso2 = "PG";
Update `country_t` SET spanish_name = "Paraguay" WHERE iso2 = "PY";
Update `country_t` SET spanish_name = "Per&uacute;" WHERE iso2 = "PE";
Update `country_t` SET spanish_name = "Filipinas" WHERE iso2 = "PH";
Update `country_t` SET spanish_name = "Isla Pitcairn" WHERE iso2 = "PN";
Update `country_t` SET spanish_name = "Polonia" WHERE iso2 = "PL";
Update `country_t` SET spanish_name = "Portugal" WHERE iso2 = "PT";
Update `country_t` SET spanish_name = "Puerto Rico" WHERE iso2 = "PR";
Update `country_t` SET spanish_name = "Qatar" WHERE iso2 = "QA";
Update `country_t` SET spanish_name = "Reuni&oacute;n" WHERE iso2 = "RE";
Update `country_t` SET spanish_name = "Rumania" WHERE iso2 = "RO";
Update `country_t` SET spanish_name = "Federaci&oacute;n Rusa" WHERE iso2 = "RU";
Update `country_t` SET spanish_name = "Ruanda" WHERE iso2 = "RW";
Update `country_t` SET spanish_name = "San Barolom&eacute;" WHERE iso2 = "BL";
Update `country_t` SET spanish_name = "Santa Elena" WHERE iso2 = "SH";
Update `country_t` SET spanish_name = "San Cristobal y Nevis" WHERE iso2 = "KN";
Update `country_t` SET spanish_name = "Santa Luc&iacute;a" WHERE iso2 = "LC";
Update `country_t` SET spanish_name = "San Mart&iacute;n" WHERE iso2 = "MF";
Update `country_t` SET spanish_name = "San Pedro y Miquel&oacute;n" WHERE iso2 = "PM";
Update `country_t` SET spanish_name = "San Vincente y Granadinas" WHERE iso2 = "VC";
Update `country_t` SET spanish_name = "Samoa" WHERE iso2 = "WS";
Update `country_t` SET spanish_name = "San Marino" WHERE iso2 = "SM";
Update `country_t` SET spanish_name = "San Tom&eacute; y Principe" WHERE iso2 = "ST";
Update `country_t` SET spanish_name = "Arabia Saudita" WHERE iso2 = "SA";
Update `country_t` SET spanish_name = "Senegal" WHERE iso2 = "SN";
Update `country_t` SET spanish_name = "Serbia" WHERE iso2 = "RS";
Update `country_t` SET spanish_name = "Seychelles" WHERE iso2 = "SC";
Update `country_t` SET spanish_name = "Sierra Leona" WHERE iso2 = "SL";
Update `country_t` SET spanish_name = "Singapur" WHERE iso2 = "SG";
Update `country_t` SET spanish_name = "Sint Maarten" WHERE iso2 = "SX";
Update `country_t` SET spanish_name = "Eslovaquia" WHERE iso2 = "SK";
Update `country_t` SET spanish_name = "Eslovenia" WHERE iso2 = "SI";
Update `country_t` SET spanish_name = "Islas Salom&oacute;n" WHERE iso2 = "SB";
Update `country_t` SET spanish_name = "Somalia" WHERE iso2 = "SO";
Update `country_t` SET spanish_name = "Sud&aacute;frica" WHERE iso2 = "ZA";
Update `country_t` SET spanish_name = "Sudo Georgia y los Islas Sandwich del Sur" WHERE iso2 = "GS";
Update `country_t` SET spanish_name = "Corea del Sur" WHERE iso2 = "KR";
Update `country_t` SET spanish_name = "Sud&aacute;n del Sur" WHERE iso2 = "SS";
Update `country_t` SET spanish_name = "Espa&ntilde;a" WHERE iso2 = "ES";
Update `country_t` SET spanish_name = "Sri Lanka" WHERE iso2 = "LK";
Update `country_t` SET spanish_name = "Sud&aacute;n" WHERE iso2 = "SD";
Update `country_t` SET spanish_name = "Surinam" WHERE iso2 = "SR";
Update `country_t` SET spanish_name = "Isla Jan Mayen y Archipi&eacute;lago de Svalbard" WHERE iso2 = "SJ";
Update `country_t` SET spanish_name = "Swazilandia" WHERE iso2 = "SZ";
Update `country_t` SET spanish_name = "Suecia" WHERE iso2 = "SE";
Update `country_t` SET spanish_name = "Suiza" WHERE iso2 = "CH";
Update `country_t` SET spanish_name = "Siria" WHERE iso2 = "SY";
Update `country_t` SET spanish_name = "Taiwan" WHERE iso2 = "TW";
Update `country_t` SET spanish_name = "Tadjikistan" WHERE iso2 = "TJ";
Update `country_t` SET spanish_name = "Tanzania" WHERE iso2 = "TZ";
Update `country_t` SET spanish_name = "Tailandia" WHERE iso2 = "TH";
Update `country_t` SET spanish_name = "Timor Oriental" WHERE iso2 = "TL";
Update `country_t` SET spanish_name = "Togo" WHERE iso2 = "TG";
Update `country_t` SET spanish_name = "Tokelau" WHERE iso2 = "TK";
Update `country_t` SET spanish_name = "Tonga" WHERE iso2 = "TO";
Update `country_t` SET spanish_name = "Trinidad y Tobago" WHERE iso2 = "TT";
Update `country_t` SET spanish_name = "T&uacute;ez" WHERE iso2 = "TN";
Update `country_t` SET spanish_name = "Turqu&iacute;a" WHERE iso2 = "TR";
Update `country_t` SET spanish_name = "Turkmenistan" WHERE iso2 = "TM";
Update `country_t` SET spanish_name = "Islas Turcas y Caicos" WHERE iso2 = "TC";
Update `country_t` SET spanish_name = "Tuvalu" WHERE iso2 = "TV";
Update `country_t` SET spanish_name = "Uganda" WHERE iso2 = "UG";
Update `country_t` SET spanish_name = "Ucrania" WHERE iso2 = "UA";
Update `country_t` SET spanish_name = "Emiratos &Aacute;rebes Unidos" WHERE iso2 = "AE";
Update `country_t` SET spanish_name = "Reino Unido" WHERE iso2 = "GB";
Update `country_t` SET spanish_name = "Estados Unidos" WHERE iso2 = "US";
Update `country_t` SET spanish_name = "Islas ultramarinas menores de Estados Unidos" WHERE iso2 = "UM";
Update `country_t` SET spanish_name = "Uruguay" WHERE iso2 = "UY";
Update `country_t` SET spanish_name = "Uzbekist&aacute;n" WHERE iso2 = "UZ";
Update `country_t` SET spanish_name = "Vanuatu" WHERE iso2 = "VU";
Update `country_t` SET spanish_name = "Ciudad del Vaticano" WHERE iso2 = "VA";
Update `country_t` SET spanish_name = "Venezuela" WHERE iso2 = "VE";
Update `country_t` SET spanish_name = "Vietnam" WHERE iso2 = "VN";
Update `country_t` SET spanish_name = "Islas Virgenes Brit&aacute;nicas" WHERE iso2 = "VG";
Update `country_t` SET spanish_name = "Islas Virgenes Americanas" WHERE iso2 = "VI";
Update `country_t` SET spanish_name = "Wallis y Futuna" WHERE iso2 = "WF";
Update `country_t` SET spanish_name = "S&aacute;hara Occidental" WHERE iso2 = "EH";
Update `country_t` SET spanish_name = "Yemen" WHERE iso2 = "YE";
Update `country_t` SET spanish_name = "Zambia" WHERE iso2 = "ZM";
Update `country_t` SET spanish_name = "Zimbabwe" WHERE iso2 = "ZW";
