update Location l, City c  set l.city_id=c.city_id where l.city = c.city_name;
update Location set location_textual=null where location_textual='NULL';
update Location set name=null where name='NULL';
update Location set description=null where description='NULL';
update Location set environment=null where environment='NULL';
update Location set continent=null where continent='NULL';
update Location set country=null where country='NULL';
update Location set region=null where region='NULL';
update Location set city=null where city='NULL';
update Location set neighborhood=null where neighborhood='NULL';
update Location set street=null where street='NULL';
update Location set street_number=null where street_number='NULL';
update Location set map_url=null where map_url='NULL';
update Location set locale=null where locale='NULL';
update Location l, City c set l.city_id=c.city_id where l.location_textual=c.city_name;
update Location l set l.city_id=3950 where l.location_textual like '%Pergine%';
update Location l set l.city_id=4015 where l.location_textual like '%Trento%';
